// Coin data and facts for Fortuna's Purse calculator

// Coin specifications
const coinData = {
    // US Silver Coins
    "1942-1945 Silver War Nickel": { weight: 5.0, purity: 0.35, metal: "silver", country: "US" },
    "1892-1916 Silver Barber Dime": { weight: 2.5, purity: 0.9, metal: "silver", country: "US" },
    "1916-1945 Silver Mercury Dime": { weight: 2.5, purity: 0.9, metal: "silver", country: "US" },
    "1946-1964 Roosevelt Silver Dime": { weight: 2.5, purity: 0.9, metal: "silver", country: "US" },
    "1892-1916 Barber Quarter": { weight: 6.25, purity: 0.9, metal: "silver", country: "US" },
    "1916-1930 Standing Liberty Quarter": { weight: 6.25, purity: 0.9, metal: "silver", country: "US" },
    "1932-1964 Washington Quarter": { weight: 6.25, purity: 0.9, metal: "silver", country: "US" },
    "1892-1915 Barber Half Dollar": { weight: 12.5, purity: 0.9, metal: "silver", country: "US" },
    "1916-1947 Walking Liberty Half Dollar": { weight: 12.5, purity: 0.9, metal: "silver", country: "US" },
    "1948-1963 Franklin Half Dollar": { weight: 12.5, purity: 0.9, metal: "silver", country: "US" },
    "1964 Kennedy Half Dollar": { weight: 12.5, purity: 0.9, metal: "silver", country: "US" },
    "1965-1970 Kennedy Half Dollar": { weight: 11.5, purity: 0.4, metal: "silver", country: "US" },
    "1878-1921 Morgan Dollar": { weight: 26.73, purity: 0.9, metal: "silver", country: "US" },
    "1921-1935 Peace Dollar": { weight: 26.73, purity: 0.9, metal: "silver", country: "US" },
    "1971-1974, 1976 Ike Dollar": { weight: 24.59, purity: 0.4, metal: "silver", country: "US" },
    "1986-2013 Silver Eagle": { weight: 31.1, purity: 0.999, metal: "silver", country: "US" },
    
    // US Gold Coins
    "1849-1854 Liberty Gold Dollar Type 1": { weight: 1.672, purity: 0.9, metal: "gold", country: "US" },
    "1854-1856 Liberty Gold Dollar Type 2": { weight: 1.672, purity: 0.9, metal: "gold", country: "US" },
    "1856-1889 Liberty Gold Dollar Type 3": { weight: 1.672, purity: 0.9, metal: "gold", country: "US" },
    "1840-1907 Liberty Quarter Eagle": { weight: 4.18, purity: 0.9, metal: "gold", country: "US" },
    "1839-1908 Liberty Half Eagle": { weight: 8.359, purity: 0.9, metal: "gold", country: "US" },
    "1908-1929 Indian Half Eagle": { weight: 8.359, purity: 0.9, metal: "gold", country: "US" },
    "1838-1907 Liberty Eagle": { weight: 16.718, purity: 0.9, metal: "gold", country: "US" },
    "1907-1933 Indian Eagle": { weight: 16.718, purity: 0.9, metal: "gold", country: "US" },
    "1849-1907 Liberty Double Eagle": { weight: 33.436, purity: 0.9, metal: "gold", country: "US" },
    "1907-1933 Saint Gaudens Double Eagle": { weight: 33.436, purity: 0.9, metal: "gold", country: "US" },
    
    // Canadian Silver Coins
    "1858–1919 Nickel": { weight: 1.17, purity: 0.925, metal: "silver", country: "Canada" },
    "1920–1921 Nickel": { weight: 1.17, purity: 0.925, metal: "silver", country: "Canada" },
    "1858–1910 Dime": { weight: 2.33, purity: 0.925, metal: "silver", country: "Canada" },
    "1910–1919 Dime": { weight: 2.33, purity: 0.925, metal: "silver", country: "Canada" },
    "1920–1966 Dime": { weight: 2.33, purity: 0.925, metal: "silver", country: "Canada" },
    "mid 1967-mid 1968 Dime": { weight: 2.33, purity: 0.8, metal: "silver", country: "Canada" },
    "1908–1910 Quarter": { weight: 5.83, purity: 0.925, metal: "silver", country: "Canada" },
    "1910–1919 Quarter": { weight: 5.83, purity: 0.925, metal: "silver", country: "Canada" },
    "1920–1952 Quarter": { weight: 5.83, purity: 0.925, metal: "silver", country: "Canada" },
    "1953–1967 Quarter": { weight: 5.83, purity: 0.925, metal: "silver", country: "Canada" },
    "mid 1967-mid 1968 Quarter": { weight: 5.83, purity: 0.8, metal: "silver", country: "Canada" },
    "1908–1919 Fifty-cent": { weight: 11.66, purity: 0.925, metal: "silver", country: "Canada" },
    "1920–1967 Fifty-cent": { weight: 11.66, purity: 0.925, metal: "silver", country: "Canada" },
    "1935–1967 Voyageur Dollar": { weight: 23.33, purity: 0.925, metal: "silver", country: "Canada" },
    
    // Canadian Gold Coins
    "1912-1914 Five Dollar": { weight: 8.36, purity: 0.9, metal: "gold", country: "Canada" },
    "1912-1914 Ten Dollar": { weight: 16.72, purity: 0.9, metal: "gold", country: "Canada" },
    
    // Mexican Silver Coins
    "1867-1905 5 Centavos": { weight: 1.25, purity: 0.9025, metal: "silver", country: "Mexico" },
    "1867-1905 10 Centavos": { weight: 2.5, purity: 0.9025, metal: "silver", country: "Mexico" },
    "1905-1914 10 Centavos": { weight: 2.5, purity: 0.9025, metal: "silver", country: "Mexico" },
    "1925-1935 10 Centavos": { weight: 2.5, purity: 0.72, metal: "silver", country: "Mexico" },
    "1898-1905 20 Centavos": { weight: 5.0, purity: 0.9025, metal: "silver", country: "Mexico" },
    "1905-1914 20 Centavos": { weight: 5.0, purity: 0.9025, metal: "silver", country: "Mexico" },
    "1920-1943 20 Centavos": { weight: 5.0, purity: 0.72, metal: "silver", country: "Mexico" },
    "1869-1890 25 Centavos": { weight: 6.25, purity: 0.9025, metal: "silver", country: "Mexico" },
    "1950-1953 25 Centavos": { weight: 6.25, purity: 0.72, metal: "silver", country: "Mexico" },
    "1869-1894 50 Centavos": { weight: 12.5, purity: 0.9025, metal: "silver", country: "Mexico" },
    "1905-1918 50 Centavos": { weight: 12.5, purity: 0.9025, metal: "silver", country: "Mexico" },
    "1919-1945 50 Centavos": { weight: 12.5, purity: 0.72, metal: "silver", country: "Mexico" },
    "1935 50 Centavos": { weight: 12.5, purity: 0.72, metal: "silver", country: "Mexico" },
    "1950-1951 50 Centavos": { weight: 12.5, purity: 0.72, metal: "silver", country: "Mexico" },
    "1869-1913 1 Peso": { weight: 27.0, purity: 0.9025, metal: "silver", country: "Mexico" },
    "1920-1945 1 Peso": { weight: 27.0, purity: 0.72, metal: "silver", country: "Mexico" },
    "1947-1948 1 Peso": { weight: 27.0, purity: 0.72, metal: "silver", country: "Mexico" },
    "1950 1 Peso": { weight: 27.0, purity: 0.72, metal: "silver", country: "Mexico" },
    "1947-1948 5 Pesos": { weight: 30.0, purity: 0.72, metal: "silver", country: "Mexico" },
    "1950-1954 5 Pesos": { weight: 30.0, purity: 0.72, metal: "silver", country: "Mexico" },
    "1955-1959 5 Pesos": { weight: 30.0, purity: 0.72, metal: "silver", country: "Mexico" },
    "1955-1960 10 Pesos": { weight: 28.5, purity: 0.72, metal: "silver", country: "Mexico" },
    "1968-1972 25 Pesos": { weight: 22.5, purity: 0.72, metal: "silver", country: "Mexico" },
    "1977-1979 100 Pesos": { weight: 27.7, purity: 0.72, metal: "silver", country: "Mexico" },
    
    // Mexican Gold Coins
    "1870-1905 1 Peso": { weight: 1.69, purity: 0.9, metal: "gold", country: "Mexico" },
    "1919-1947 2 Pesos": { weight: 1.66, purity: 0.9, metal: "gold", country: "Mexico" },
    "1870-1892 2-1/2 Pesos": { weight: 4.22, purity: 0.9, metal: "gold", country: "Mexico" },
    "1918-1948 2-1/2 Pesos": { weight: 2.08, purity: 0.9, metal: "gold", country: "Mexico" },
    "1870-1905 5 Pesos": { weight: 8.44, purity: 0.9, metal: "gold", country: "Mexico" },
    "1905-1955 5 Pesos": { weight: 4.16, purity: 0.9, metal: "gold", country: "Mexico" },
    "1870-1905 10 Pesos": { weight: 16.88, purity: 0.9, metal: "gold", country: "Mexico" },
    "1905-1959 10 Pesos": { weight: 8.33, purity: 0.9, metal: "gold", country: "Mexico" },
    "1870-1905 20 Pesos": { weight: 33.76, purity: 0.9, metal: "gold", country: "Mexico" },
    "1917-1959 20 Pesos": { weight: 16.67, purity: 0.9, metal: "gold", country: "Mexico" },
    "1921-1947 50 Pesos": { weight: 41.67, purity: 0.9, metal: "gold", country: "Mexico" },
};

// Complete coin facts for all coins
const coinFacts = {
    // US Silver Coins
    "1942-1945 Silver War Nickel": "The Silver War Nickel, minted from 1942 to 1945, was a unique coin created in response to World War II. Unlike traditional nickels, these contained 35% silver, 56% copper, and 9% manganese, resulting in a distinctive silver-colored appearance. The change in composition was due to nickel being a strategic war material. These coins can be easily identified by the large mint mark above Monticello on the reverse side, a feature not seen on other Jefferson nickels.",
    "1892-1916 Silver Barber Dime": "The Barber Dime, designed by Chief Engraver Charles E. Barber, was minted from 1892 to 1916. It features Liberty wearing a crown of laurel and oak leaves on the obverse, symbolizing civil and military glory. The reverse displays a wreath enclosing the denomination. These dimes are composed of 90% silver and 10% copper, making them valuable for both their silver content and historical significance.",
    "1916-1945 Silver Mercury Dime": "The Mercury Dime, also known as the Winged Liberty Head Dime, was minted from 1916 to 1945. Designed by Adolph A. Weinman, it features a young Liberty wearing a winged cap, often mistaken for the Roman god Mercury. The reverse shows a fasces and an olive branch, symbolizing unity and strength with peace. Like its predecessor, it's 90% silver and 10% copper, making it a popular choice among silver collectors.",
    "1946-1964 Roosevelt Silver Dime": "The Roosevelt Dime, introduced in 1946 to honor President Franklin D. Roosevelt, continued the 90% silver composition until 1964. Designed by John R. Sinnock, it features Roosevelt's portrait on the obverse and a torch flanked by olive and oak branches on the reverse, symbolizing liberty, peace, and victory. These dimes are the last circulating U.S. dimes to contain silver, marking the end of an era in American coinage.",
    "1892-1916 Barber Quarter": "The Barber Quarter, part of the Barber coinage series, was minted from 1892 to 1916. Like its dime counterpart, it was designed by Charles E. Barber and features Liberty on the obverse and an eagle on the reverse. Composed of 90% silver and 10% copper, these quarters have a higher silver content than modern quarters, making them valuable to both collectors and silver enthusiasts.",
    "1916-1930 Standing Liberty Quarter": "The Standing Liberty Quarter, designed by Hermon Atkins MacNeil, was minted from 1916 to 1930. It features a standing Liberty figure on the obverse and an eagle in flight on the reverse. The design underwent modifications in 1917, most notably covering Liberty's exposed breast. These quarters are 90% silver and 10% copper, and are known for their beautiful, intricate design.",
    "1932-1964 Washington Quarter": "The Washington Quarter, introduced in 1932 to commemorate the 200th anniversary of George Washington's birth, continued to be minted with 90% silver content until 1964. Designed by John Flanagan, it features Washington's portrait on the obverse and an eagle on the reverse. These quarters are popular among collectors for their historical significance and silver content.",
    "1892-1915 Barber Half Dollar": "The Barber Half Dollar, part of the Barber coinage series, was minted from 1892 to 1915. Designed by Charles E. Barber, it features Liberty on the obverse and an eagle on the reverse, similar to the quarter but larger. Composed of 90% silver and 10% copper, these half dollars contain a significant amount of silver, making them valuable to collectors and silver investors alike.",
   "1916-1947 Walking Liberty Half Dollar": "The Walking Liberty Half Dollar, designed by Adolph A. Weinman, was minted from 1916 to 1947. It features a full-length figure of Liberty walking towards the dawn of a new day on the obverse, and an eagle perched on a mountain crag on the reverse. Considered one of the most beautiful American coins, it's composed of 90% silver and 10% copper, making it highly sought after by both collectors and silver enthusiasts.",
    "1948-1963 Franklin Half Dollar": "The Franklin Half Dollar, minted from 1948 to 1963, features Benjamin Franklin on the obverse and the Liberty Bell on the reverse. Designed by John R. Sinnock, it was the first U.S. coin to depict a real person other than a president. Like its predecessors, it's composed of 90% silver and 10% copper, making it valuable for its silver content as well as its historical significance.",
    "1964 Kennedy Half Dollar": "The 1964 Kennedy Half Dollar was introduced shortly after President John F. Kennedy's assassination. Designed by Gilroy Roberts and Frank Gasparro, it features Kennedy's portrait on the obverse and the Presidential Seal on the reverse. This first year of issue is significant as it's the only year the Kennedy Half Dollar was minted in 90% silver for general circulation, making it particularly valuable to collectors and silver enthusiasts.",
    "1965-1970 Kennedy Half Dollar": "From 1965 to 1970, the Kennedy Half Dollar continued to be minted but with a reduced silver content. These coins contain 40% silver and 60% copper, a transition between the 90% silver coins and the copper-nickel clad coins that followed. Despite the reduced silver content, these coins are still valued by collectors and contain a significant amount of precious metal.",
    "1878-1921 Morgan Dollar": "The Morgan Dollar, designed by George T. Morgan, was minted from 1878 to 1904 and again in 1921. It features a profile of Liberty on the obverse and an eagle on the reverse. Composed of 90% silver and 10% copper, these large coins contain a substantial amount of silver. They're highly prized by collectors for their historical significance, beautiful design, and silver content.",
    "1921-1935 Peace Dollar": "The Peace Dollar, designed by Anthony de Francisci, was minted from 1921 to 1935. It features a young Lady Liberty on the obverse and an eagle perched on a rock on the reverse, with the word 'PEACE' inscribed below. Like the Morgan Dollar, it's composed of 90% silver and 10% copper. The Peace Dollar symbolizes America's coming of age as a world power after World War I.",
    "1971-1974, 1976 Ike Dollar": "The Eisenhower Dollar, or 'Ike Dollar,' was minted from 1971 to 1974 and again in 1976 for the U.S. Bicentennial. While the general circulation coins were made of copper-nickel clad, special collector versions were minted in 40% silver. These silver versions are composed of an outer layer of 80% silver and 20% copper, bonded to an inner core of 20.9% silver and 79.1% copper, resulting in an overall silver content of 40%.",
    "1986-2013 Silver Eagle": "The American Silver Eagle, first minted in 1986, is the official silver bullion coin of the United States. Each coin contains one troy ounce of 99.9% pure silver. The obverse features Adolph A. Weinman's 'Walking Liberty' design, while the reverse showcases a heraldic eagle with shield designed by John Mercanti. Unlike circulating coins, Silver Eagles are investment-grade bullion coins, prized for their silver content and guaranteed by the U.S. government.",
    
    // US Gold Coins
    "1849-1854 Liberty Gold Dollar Type 1": "This small gold coin was the smallest denomination of gold currency ever minted in the US. Composed of 90% gold and 10% copper, it weighed 1.672 grams. The obverse featured a left-facing portrait of Liberty, while the reverse displayed the denomination and date within a wreath.",
    "1854-1856 Liberty Gold Dollar Type 2": "This short-lived version of the gold dollar featured a redesigned, larger head of Liberty wearing a feathered headdress. It maintained the 90% gold content and 1.672-gram weight of its predecessor.",
    "1856-1889 Liberty Gold Dollar Type 3": "The final version of the gold dollar, this coin featured a smaller head of Liberty with a different design. It kept the same weight and composition as the previous versions.",
    "1840-1907 Liberty Quarter Eagle": "This $2.50 gold coin featured a classical Liberty head design on the obverse and an eagle on the reverse. It was 90% gold, 10% copper, and weighed 4.18 grams.",
    "1839-1908 Liberty Half Eagle": "The $5 gold coin of this period featured a similar design to the Quarter Eagle. It was 90% gold and weighed 8.359 grams.",
    "1908-1929 Indian Half Eagle": "This redesigned $5 gold coin featured a Native American head on the obverse and an eagle on the reverse. It maintained the same weight and composition as its predecessor.",
    "1838-1907 Liberty Eagle": "The $10 gold coin of this era featured the Liberty head design. It was 90% gold and weighed 16.718 grams.",
    "1907-1933 Indian Eagle": "The redesigned $10 gold coin featured a Native American head on the obverse and a standing eagle on the reverse. It kept the same weight and gold content as the Liberty Eagle.",
    "1849-1907 Liberty Double Eagle": "This $20 gold coin was the largest regular issue gold coin in US history. It featured the Liberty head design, was 90% gold, and weighed 33.436 grams.",
    "1907-1933 Saint Gaudens Double Eagle": "Considered one of the most beautiful US coins ever minted, this $20 gold coin featured a full-length Liberty figure on the obverse and a flying eagle on the reverse. It maintained the same weight and gold content as its predecessor.",
    
    // Canadian Silver Coins
    "1858–1919 Nickel": "Despite its name, this coin was made of silver. It contained 92.5% silver and 7.5% copper, weighing 1.17 grams. The obverse featured the reigning British monarch, while the reverse displayed a crown and wreath design. This coin marked Canada's transition from British colonial currency to its own decimal system.",
    "1920–1921 Nickel": "This coin maintained the same silver content (92.5%) and weight (1.17 grams) as its predecessor. The design remained largely the same, featuring King George V on the obverse. These were the last silver 'nickels' before Canada switched to actual nickel for this denomination in 1922.",
    "1858–1910 Dime": "The first Canadian dimes were 92.5% silver and 7.5% copper, weighing 2.33 grams. The obverse featured Queen Victoria (until 1901), then King Edward VII. The reverse typically displayed a wreath of maple leaves, embodying Canadian identity.",
    "1910–1919 Dime": "These dimes maintained the same silver content and weight. The obverse now showed King George V. The reverse design remained consistent with the previous period, featuring the wreath of maple leaves.",
    "1920–1966 Dime": "Still 92.5% silver and 7.5% copper, weighing 2.33 grams. In 1937, the reverse design changed to feature the famous Bluenose schooner, which became an iconic Canadian image. This design continued until 1966.",
    "mid 1967-mid 1968 Dime": "During this transitional period, dimes were minted with 80% silver and 20% copper, weighing 2.33 grams. The Bluenose design was replaced with a mackerel to commemorate Canada's centennial in 1967.",
    "1908–1910 Quarter": "These quarters were 92.5% silver and 7.5% copper, weighing 5.83 grams. The obverse featured King Edward VII, while the reverse displayed the Canadian coat of arms.",
    "1910–1919 Quarter": "Maintaining the same silver content and weight, these quarters now featured King George V on the obverse. The reverse design remained the Canadian coat of arms.",
    "1920–1952 Quarter": "Still 92.5% silver and 7.5% copper, weighing 5.83 grams. In 1937, the reverse design changed to feature a caribou head, which became another iconic Canadian coin design.",
    "1953–1967 Quarter": "These quarters maintained the 92.5% silver content and 5.83 gram weight. The obverse now featured Queen Elizabeth II, while the reverse retained the caribou design.",
    "mid 1967-mid 1968 Quarter": "During this transitional period, quarters were minted with 80% silver and 20% copper, still weighing 5.83 grams. For 1967, the reverse featured a bobcat design to commemorate Canada's centennial.",
    "1908–1919 Fifty-cent": "These large coins were 92.5% silver and 7.5% copper, weighing 11.66 grams. The obverse featured King Edward VII (1908-1910) and then King George V (1911-1919). The reverse displayed the Canadian coat of arms.",
    "1920–1967 Fifty-cent": "Maintaining the same 92.5% silver content and 11.66 gram weight. The design remained largely the same, with updates to the monarch's effigy as reigns changed. The Canadian coat of arms on the reverse was updated in 1937 to a more modern design.",
    "1935–1967 Voyageur Dollar": "This iconic Canadian silver dollar was 80% silver and 20% copper (1935-1967), weighing 23.33 grams. The obverse featured the reigning monarch, while the reverse displayed the famous 'voyageur' design - a canoe carrying a voyageur and an Indigenous person, representing Canada's early fur trade and exploration history. This design symbolized cooperation between European settlers and Indigenous peoples.",
    
    // Canadian Gold Coins
    "1912-1914 Five Dollar": "The 1912-1914 Canadian Five Dollar gold coin was part of Canada's first gold coin series. It contained 0.2419 troy ounces of pure gold and featured King George V on the obverse and the Canadian coat of arms on the reverse.",
    "1912-1914 Ten Dollar": "The 1912-1914 Canadian Ten Dollar gold coin was the larger denomination in Canada's first gold coin series. It contained 0.4838 troy ounces of pure gold and displayed King George V on the obverse and the Canadian coat of arms on the reverse.",
    
    // Mexican Silver Coins
    "1867-1905 5 Centavos": "This small silver coin was minted during the early years of Mexico's independence. Composed of 90.25% silver and 9.75% copper, it weighed approximately 1.25 grams. The obverse typically featured the Mexican coat of arms, while the reverse displayed the denomination within a wreath.",
    "1867-1905 10 Centavos": "Similar in design to the 5 Centavos, this coin was also 90.25% silver and 9.75% copper, weighing about 2.5 grams. It played a crucial role in daily transactions during Mexico's economic growth in the late 19th century.",
    "1905-1914 10 Centavos": "This version of the 10 Centavos maintained the 90.25% silver content but saw slight design changes. The obverse now featured a more detailed rendition of the Mexican coat of arms, reflecting the country's evolving national identity.",
    "1925-1935 10 Centavos": "During this period, the silver content was reduced to 72%, with the coin weighing about 2.5 grams. The design was updated to include an eagle on the obverse, symbolizing Mexican independence and strength.",
    "1898-1905 20 Centavos": "This coin was 90.25% silver and 9.75% copper, weighing approximately 5 grams. It featured the national coat of arms on the obverse and the denomination within a wreath on the reverse, similar to other denominations of the era.",
    "1905-1914 20 Centavos": "Maintaining the 90.25% silver content and 5-gram weight, this version saw updated designs reflecting the changing political landscape of Mexico during the early 20th century.",
    "1920-1943 20 Centavos": "The silver content was reduced to 72% during this period, with the coin weighing about 5 grams. The design often featured an eagle on the obverse, symbolizing Mexican resilience during turbulent times.",
    "1869-1890 25 Centavos": "This early 25 Centavos coin was 90.25% silver and 9.75% copper, weighing approximately 6.25 grams. It played a significant role in Mexico's economy during a period of modernization and foreign investment.",
    "1950-1953 25 Centavos": "By this time, the silver content had been reduced to 72%, with the coin weighing about 6.25 grams. The design often featured pre-Columbian motifs, reflecting Mexico's growing emphasis on its indigenous heritage.",
    "1869-1894 50 Centavos": "This half-peso coin was 90.25% silver and 9.75% copper, weighing approximately 12.5 grams. It featured intricate designs, often including the national coat of arms and allegorical figures representing liberty or progress.",
    "1905-1918 50 Centavos": "Maintaining the 90.25% silver content and weight of its predecessor, this coin saw design updates reflecting Mexico's centennial of independence and the tumultuous period of the Mexican Revolution.",
    "1919-1945 50 Centavos": "During this period, the silver content was reduced to 72%, with the coin weighing about 12.5 grams. The designs often reflected Mexico's post-revolutionary identity, featuring indigenous motifs and symbols of progress.",
    "1935 50 Centavos": "This special issue commemorative coin was minted to celebrate the 25th anniversary of the Mexican Revolution. It was 72% silver and featured unique designs related to the revolution.",
    "1950-1951 50 Centavos": "By this time, the silver content had been reduced to 72%, with the coin weighing about 12.5 grams. The design often incorporated pre-Columbian art, reflecting Mexico's emphasis on its ancient heritage.",
    "1869-1913 1 Peso": "This silver peso was 90.25% silver and 9.75% copper, weighing approximately 27 grams. It featured various designs over the years, including portraits of national heroes and allegorical figures representing liberty.",
    "1920-1945 1 Peso": "During this period, the silver content was reduced to 72%, with the coin weighing about 27 grams. The designs often reflected Mexico's post-revolutionary ideals and cultural heritage.",
    "1947-1948 1 Peso": "This coin was 72% silver and 28% copper, weighing about 27 grams. It often featured the iconic 'Balance Scale' design, symbolizing justice and equality in post-war Mexico.",
    "1950 1 Peso": "Similar to the 1947-1948 issue in composition and weight, this coin often featured designs celebrating Mexico's pre-Columbian heritage and featured 72% silver content.",
    "1947-1948 5 Pesos": "This larger denomination was 72% silver and 28% copper, weighing approximately 30 grams. It often featured portraits of national heroes or significant historical events in Mexico's history.",
    "1950-1954 5 Pesos": "Maintaining the 72% silver content and 30-gram weight, these coins often featured designs celebrating Mexico's cultural and historical heritage, particularly its indigenous roots.",
    "1955-1959 5 Pesos": "This issue maintained the 72% silver content, weighing about 30 grams. The designs continued to celebrate Mexican history and culture, often featuring important national symbols.",
    "1955-1960 10 Pesos": "This higher denomination coin was 72% silver and 28% copper, weighing approximately 28.5 grams. It often featured significant historical figures or events in Mexican history.",
    "1968-1972 25 Pesos": "Minted for the 1968 Olympics in Mexico City, this coin was 72% silver and weighed about 22.5 grams. It featured various Olympic-themed designs, celebrating Mexico's role as host country.",
    "1977-1979 100 Pesos": "This large silver coin was 72% silver and weighed approximately 27.7 grams. It was often minted as a commemorative issue, celebrating significant events or figures in Mexican history.",
    
    // Mexican Gold Coins
    "1870-1905 1 Peso": "The 1870-1905 1 Peso gold coin was part of Mexico's early decimal currency system. It contained 0.0487 troy ounces of pure gold (90% purity) and weighed approximately 1.69 grams. The design typically featured the Mexican eagle on the obverse.",
    "1919-1947 2 Pesos": "The 1919-1947 2 Pesos gold coin featured the Mexican coat of arms and contained 0.0479 troy ounces of pure gold (90% purity). It weighed approximately 1.66 grams and was a popular smaller denomination gold coin.",
    "1870-1892 2-1/2 Pesos": "The 1870-1892 2-1/2 Pesos gold coin was an early denomination in Mexico's gold coinage, containing 0.1218 troy ounces of pure gold (90% purity). It weighed approximately 4.22 grams and featured the national emblem.",
    "1918-1948 2-1/2 Pesos": "The 1918-1948 2-1/2 Pesos gold coin featured the Winged Victory design (El Ángel de la Independencia) and contained 0.0601 troy ounces of pure gold (90% purity). It weighed approximately 2.08 grams.",
    "1870-1905 5 Pesos": "The 1870-1905 5 Pesos gold coin was a larger denomination in early Mexican gold coinage, containing 0.2437 troy ounces of pure gold (90% purity). It weighed approximately 8.44 grams.",
    "1905-1955 5 Pesos": "The 1905-1955 5 Pesos gold coin featured updated designs and contained 0.1201 troy ounces of pure gold (90% purity). It weighed approximately 4.16 grams and often featured the head of liberty.",
    "1870-1905 10 Pesos": "The 1870-1905 10 Pesos gold coin was a significant denomination in early Mexican gold coinage, containing 0.4874 troy ounces of pure gold (90% purity). It weighed approximately 16.88 grams.",
    "1905-1959 10 Pesos": "The 1905-1959 10 Pesos gold coin featured the Cap and Rays design and contained 0.2411 troy ounces of pure gold (90% purity). It weighed approximately 8.33 grams.",
    "1870-1905 20 Pesos": "The 1870-1905 20 Pesos gold coin was one of the largest denominations in early Mexican gold coinage, containing 0.9749 troy ounces of pure gold (90% purity). It weighed approximately 33.76 grams.",
    "1917-1959 20 Pesos": "The 1917-1959 20 Pesos gold coin featured the Aztec Calendar design on the reverse and contained 0.4823 troy ounces of pure gold (90% purity). It weighed approximately 16.67 grams and is one of Mexico's most iconic gold coin designs.",
    "1921-1947 50 Pesos": "The 1921-1947 50 Pesos gold coin, also known as the Centenario, was Mexico's largest gold coin, containing 1.2057 troy ounces of pure gold (90% purity). It weighed approximately 41.67 grams. The obverse features Winged Victory (El Ángel de la Independencia) and the reverse shows the Mexican coat of arms. It was issued to commemorate the 100th anniversary of Mexico's independence from Spain."
};